### ISSUE TITLE
MAP-NAME predicate not fully implemented?

### ISSUE THREAD

**Issue by fairlight1337** [cram2/cram_semantic_maps#4]
[This line](https://github.com/cram2/cram_semantic_maps/blob/master/cram_semantic_map_utils/src/semantic-map.lisp#L326) refers to a prolog predicate called `map_name` (although in the adjacent error message it refers to it as `MAP-NAME`) which was not explained anywhere. I wasn't able to find it in [iai_maps](https://github.com/code-iai/iai_maps). What is its intended purpose and where is it defined? Is it meant to return the identifier of a map to double-check whether the correct OWL was loaded for the current CRAM package? And if yes, why was it changed from the way it was done [before](https://github.com/cram-code/cram_highlevel/blob/master/cl_semantic_map_utils/src/semantic-map.lisp#L309) which worked fine all the time?

If this is a change indented to stay, I'd suggest properly documenting it and implementing the required prolog predicates as part of iai_maps. In its current state, it simply breaks semantic map usage.

**Comment by fairlight1337** [comment]
Found it. It is part of [knowrob_map_tools](https://github.com/knowrob/knowrob/tree/master/knowrob_map_tools) and is defined [here](https://github.com/knowrob/knowrob/blob/master/knowrob_map_tools/prolog/semantic_map_utils.pl#L269). According to this, an individual of type `SemanticEnvironmentMap` needs to be defined, so this double-check should be fine as CRAM checks for the exact same thing; I see now why its there.

The same file raises another question though: `map_name` and `map_instance` ([line 260](https://github.com/knowrob/knowrob/blob/master/knowrob_map_tools/prolog/semantic_map_utils.pl#L260)) are doing *exactly* the same thing, while `map_instance` has been around for a couple of years already. Is one of them supposed to get more functionality? @yazdani git blame tells me that this was your change.

**Comment by gaya-** [comment]
@fairlight1337 Was this issue resolved? I see now that `map_name` and `map_instance` are the same thing. Do we want to switch to `map_instance` on the CRAM side and get rid of `map_name`?

**Comment by fairlight1337** [comment]
Yeah, I closed it due to the original problem being solved (i.e. map validation not working, which is now due to changes in the semantic map).

But the matter of the two identical predicates is still there, right. @yazdani and me talked and thought it might be good to either make the one refer to the other, or remove one and change all occurrences of the respective Prolog calls. Lazily we could do the former, but actually we should do the latter. Haven't gotten the time to think about that any further or take any action yet.

**Comment by gaya-** [comment]
@yazdani Should we switch to `map_instance`? I like `map_name` better for the predicate though, but I'm not sure who else uses `map_instance`. Should we try to get rid of `map_instance` and see if it breaks anything?

**Comment by gaya-** [comment]
@bbrieber

**Comment by yazdani** [comment]
Well, I donot know, yesterday we talked about this issue. I think Jan uses map_instance. @fairlight1337 Am I right?

**Comment by fairlight1337** [comment]
I'm fine either way, you guys just have your way. Right now I use map_instance, but only once I think. So I'm flexible there.

**Comment by bbrieber** [comment]
From my point of view map_instance is less confusing than map_name, because the IRI of the map is actually not the "name". The instance seems to be more accurate for me. From the owl syntax map_individual vould even be better...  maybe also @daniel86 has an opinion about this issue...

**Comment by gaya-** [comment]
So, @daniel86, any ideas on how to call the predicate that returns the OWL name of the map instance?

**Comment by daniel86** [comment]
I vote for `map_instance`

**Comment by fairlight1337** [comment]
:+1:

**Comment by gaya-** [comment]
Ok, I will make a PR for CRAM side in the evening and you guys can then get rid of `map_name` if nobody objects. @yazdani and @fairlight1337 can then test the PR.
